Добавляет верстку страниц
htmlacademy-htmlcss/2097425-sedona-34 pull request #2
Opened 2022-06-07 10:29 UTC by sashadudkina5

2022-06-07 16:49 UTC, jumile requested changes
В целом вы очень хорошо справились с заданием. Внимательно добавили все блоки в разметку, почти ничего не пропустили. Грамотно применяли классы, названия большинства классов отражают функциональное назначение блоков - это правильно. Но сразу же хочу отметить, что не всем блокам "хватило" классов. Например, на странице несколько section. В макете их внешний вид различается - значит, вы будете стилизовать их по-разному, а для этого у каждого должен быть свой класс. То же самое можно сказать про списки, ссылки и абзацы.
И еще важный момент: внимательно прочитайте критерий PROJ-01 (https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-01) и соблюдайте размер отступов и вложенность блоков в разметке.

2022-06-07 16:49 UTC, jumile commented on index.html
> +  <ul class="navogation-list">
Вот тут опечатку (navOgation) лучше исправить, а то потом при стилизации можно долго искать ошибку.

2022-06-07 16:49 UTC, jumile commented on index.html
> +    <li>
А здесь точно класс не нужен?

2022-06-07 16:49 UTC, jumile commented on index.html
> +<ul class="navogation-list navigation-user">
Опечатку (navOgation) лучше исправить.

2022-06-07 16:49 UTC, jumile commented on index.html
> +    <a class="navigation-link" href="#"><span class="visually-hidden">Избранное</span></a>
Здесь не хватает блока с числом 12.

2022-06-07 16:49 UTC, jumile commented on index.html
> +    <a class="navigation-link" href="#">Хочу сюда!</a>
Саша, обратите внимание: эта ссылка совершенно точно будет отличаться от всех остальных, она похожа на кнопку. Поэтому неоправданно присваивать ей такой же класс, как ссылкам в меню. Лучше придумать другой, который будет точно указывать, что это кнопка.

2022-06-07 16:49 UTC, jumile commented on index.html
> +  <section class="advanates">
Опечатка? advantages?

2022-06-07 16:49 UTC, jumile commented on index.html
> +    <img class="logo" src="" alt="Фотография Седоны">
Название класса .logo, мне кажется, здесь не самый лучший вариант - ведь это не логотип Седоны. Логотип был выше, и ему класс с таким именем вполне можно присвоить, чтобы было понятно, что это картинка с логотипом. А здесь класс пока лучше убрать - в следующем разделе вы выберете ему имя, когда поймете, какое там будет изображение.

2022-06-07 16:49 UTC, jumile commented on index.html
> +      </li>>
Лишняя скобка

2022-06-07 16:49 UTC, jumile commented on index.html
> +      <li>
А у этого li будет класс? У остальных же есть.

2022-06-07 16:49 UTC, jumile commented on index.html
> +      </li class="advantages-item">
В закрывающем теге атрибуты никогда не пишут. Закрывающий тег просто указывает на конец блока.
Если я правильно поняла, здесь "объединились" закрывающий и открывающий теги для двух соседних пунктов списка. Поправьте, пожалуйста.

2022-06-07 16:49 UTC, jumile commented on index.html
> +      <p span="advantages-description">— №1 —</p>
У тега р нет атрибута span. Я правильно понимаю, что вместо span здесь имелся в виду class? Посмотрите ниже, так много где такое встречается.

2022-06-07 16:49 UTC, jumile commented on index.html
> +  <p span="interested">Заинтересовались?</p>
Раздел section должен начинаться с заголовка - см. критерий HTML-02

2022-06-07 16:49 UTC, jumile commented on index.html
> +  <div class="footer-background">
Название footer-background описывает ВНЕШНИЙ вид блока - часть футера с фоном, правильно я понимаю? Не следует описывать в названиях классов внешний вид блока, лучше указать его функционал, т.е. для чего этот блок предназначен. Здесь у нас блок с формой подписки, вот это и следует отразить в названии класса, например, footer-subscribe или подобное.  Кстати, здесь вместо div можно использовать section, ведь блок начинается с заголовка. Это сделает разметку более семантичной.

2022-06-07 16:49 UTC, jumile commented on index.html
> +     <form class="newsletter-form">
Атрибуты action и method для формы нужно обязательно указывать.  Для метода укажите здесь post, т.к. предполагается отправка формы на сервер, а для action можно указать тестовый адрес https://echo.htmlacademy.ru/ - это позволит проверить работоспособность формы.

2022-06-07 16:49 UTC, jumile commented on index.html
> +       <input type="email" action="up.htmlacademy.ru" method="post" placeholder="Ваш e-mail">
А здесь как раз action и method не нужны, эти атрибуты пишут только тегу form, т.е. форме в целом.
Обратите внимание, что у каждого input должен быть label. Это нужно для обеспечения доступности полей формы. Если label нет в макете, его следует сделать скрытым. Подробнее написано здесь: https://up.htmlacademy.ru/htmlcss/34/module/2/item/6/4 , а также в критерии HTML-05.

2022-06-07 16:49 UTC, jumile commented on index.html
> +<section>
section должен начинаться с заголовка. Здесь лучше использовать address - он предназначен как раз для контактов.

2022-06-07 16:49 UTC, jumile commented on index.html
> +<section>
section должен начинаться с заголовка. Здесь его использование ошибочно. Можно заменить на div или вовсе отказаться от обертки.

2022-06-07 16:49 UTC, jumile commented on index.html
> +        <img src="" alt="Логотип">
Когда изображения еще нет, а тег добавить надо, в атрибут src надо прописать заглушку (#):  src="#"

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +        <ul class="navogation-list">
опечатка

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +          <a href="index.html">
Эта ссылка - часть "хлебных крошек". Ее нужно включить в список.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +           <ul class="breadcumbs">
В хлебных крошках важен порядок ссылок, поэтому здесь корректнее будет упорядоченный список ol

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +             <li class="breadcumbs-item">Гостиницы</li>
Это гиперссылка, добавьте ее, пожалуйста.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +   <fieldset>
Вся эта часть - форма (form), поэтому добавьте этот тег и не забудьте про action и method

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +      <label for="pool">Scales</Бассейн>
Непонятная разметка - также в строках 65, 67 и в переключателях. 
Кстати, флажки и переключатели обычно просто оборачивают в их label.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +    <div class="infrustructure-list">
Это лишняя обертка. Здесь есть тег fieldset - он как раз предназначен для группировки элементов формы. Лучше использовать его.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +      <input type="radio" id="pool" name="livingtype" checked>
Значение каждого id на странице должно быть уникальным. pool уже использовался.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +  <input type="radio" id="Apartments" name="livingtype">
Код пишут маленькими буквами, исправьте id, пожалуйста.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +    <p>Сбросить</p>
Это тоже кнопка)), тип reset

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +<p>Найдено гостиниц: 38</p>
section должен начинаться с заголовка.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +<a href="#" class="button button-left">
button-left не отражает предназначение кнопки. Это же показ карточек, вот это и нужно отразить в названии класса.
То же самое - про 2 следующие кнопки.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +    <span class="visually-hidden">Одно предложение на странице</span>
Здесь имеется в виду Показ в виде галереи

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +        <a class="product-card-link" href="product.html">
Страницы product.html у нас не будет, поэтому адрес здесь писать не надо, поставьте заглушку #.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +          <a class="product-card-button button" href="#">Подробнее</a>
Вот это неверно: у вас вся карточка обернута в ссылку, и вы внутрь добавляете еще ссылки. Вкладывать интерактивные элементы (ссылки, кнопки) внутрь других интерактивных элементов нельзя, это может привести к их неправильной работе. Поэтому либо откажитесь от оборачивания всей карточки в ссылку, либо закройте эту общую ссылку до кнопок.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +              <span class="visually-hidden">Предыдущая страница</span>
А у нас в макете нет предыдущей страницы))

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +          <select class="numer-of-hotels-select" aria-label="Сортировка">
Этот список не для сортировки, так что aria-label неверный.
В названиях классов следует использовать английские слова, согласно критерию PROJ-02 (https://up.htmlacademy.ru/htmlcss/34/criteries#PROJ-02), поэтому numer- не подходит.

2022-06-07 16:49 UTC, jumile commented on catalog.html
> +      <ul class="navogation-list navigation-user">
опечатка

2022-06-07 19:44 UTC, sashadudkina5 commented on index.html
> +    <li>
Не совсем поняла этот момент. Он нужен (вроде есть) или наоборот не нужен, потому что итак есть класс в header ?

2022-06-07 19:47 UTC, sashadudkina5 commented on index.html
> +    <a class="navigation-link" href="#">Хочу сюда!</a>
спасибо!

2022-06-08 15:22 UTC, jumile commented on index.html
> +    <li>
Я имела в виду у тега li. Посмотрите, у  Вас у всех остальных пунктов списка класс есть, а у этого почему-то нет.

2022-06-08 16:53 UTC, jumile approved these changes
Саша, вы проделали огромную работу, молодец! Продолжайте в том же духе)) 
Хотя в коде есть недочеты, я принимаю домашку, чтобы не затягивать время, а вы поправите их в следующей работе.

2022-06-08 16:53 UTC, jumile commented on catalog.html
> +          <li>
Все-таки класс не нужен? А как мы поймем, что этот пункт списка - часть меню, и что он особенный, т.к. в нем логотип, а не ссылка?

2022-06-08 16:53 UTC, jumile commented on index.html
> +          <h3>Жильё</h3>advantages-item
Кажется, тут лишний текст.

2022-06-08 16:53 UTC, jumile commented on index.html
> +        <button class="newsletter-button" type="submit"><label for="subscribe">Подписаться</label></button>
Label у нас должен относиться к input, к текстовому полю. Представьте: скринридер читает форму для человека, который не может ее видеть. Он зачитывает label, дальше озвучивает наличие текстового поля. А тут label попал внутрь кнопки. Т.е. вам нужно перенести label из кнопки к input; в макете подписи к полю не видно - значит, label нужно скрыть (visually-hidden), чтобы его видели только скринридеры. 
С кнопкой ничего делать не нужно, она в подписи не нуждается, потому что у нее есть тип и текст внутри button, для доступности этого достаточно.

2022-06-08 16:53 UTC, jumile commented on index.html
> +    <article class="contacts">
Тег article содержит внутри себя статью - т.е. связный текст на какую-то тему, причем этот текст можно безболезненно перенести на другую страницу сайта или даже на другой сайт, этот текст как бы самодостаточен. В данном случае у нас номер телефона, который на статью не похож, так что article тут избыточен. Тега address вполне достаточно. Он тоже является семантическим элементом и предназначен как раз для контактов.

2022-06-08 16:53 UTC, jumile commented on catalog.html
> +        </form>
Форма закончилась рановато - ведь дальше еще идут переключатели и кнопки. Части "Тип жилья" и в дальнейшем "Стоимость" можно тоже оформить как fieldset, ведь у вас все очень правильно сделано по разметке, только не включено в форму. Новую форму здесь создавать не надо, это все одна и та же.

2022-06-08 16:53 UTC, jumile commented on catalog.html
> +
Вот здесь должен быть /form

2022-06-08 16:53 UTC, jumile commented on catalog.html
> +          <li class="favourites-chosen">12</li>
Смотрите, как делают такие штуки: есть ссылка на Избранное, в ней будет иконка, добавленная через CSS. Подпись "Избранное" добавляется через span и потом будет скрыта. И вот внутрь этой ссылки еще одним span мы добавляем число 12. Т.е. не отдельным элементом, а как часть Избранного.

2022-06-08 16:53 UTC, jumile commented on catalog.html
> +          <span class="visually-hidden">Показать список</span>
В строках 106-111 потерялся закрывающий а.

2022-06-08 16:53 UTC, jumile commented on index.html
> +        </li>
Смотрите, как делают такие штуки: есть ссылка на Избранное, в ней будет иконка, добавленная через CSS. Подпись "Избранное" добавляется через span и потом будет скрыта. И вот внутрь этой ссылки еще одним span мы добавляем число 12. Т.е. не отдельным элементом, а как часть Избранного.

2022-06-08 16:53 UTC, jumile commented on catalog.html
> +            <button class="newsletter-button" type="submit"><label for="subscribe">Подписаться</label></button>
Тег label попал не туда - написала для index.html

2022-06-08 16:55 UTC, merged

2022-06-09 11:14 UTC, sashadudkina5 commented on index.html
> +    <article class="contacts">
спасибо!