Добавляет графику и вносит правки в разметку
htmlacademy-htmlcss/2097425-sedona-34 pull request #3
Opened 2022-06-09 12:02 UTC by sashadudkina5

2022-06-09 16:23 UTC, jumile requested changes
Очень хорошо! Рада, что вы разобрались с путями к файлам, это сложный вопрос. 
Теперь о недочетах: размеры изображений в дробных пикселях не задают, так что округляйте. Это для многих изображений встречается, поправьте, пожалуйста. 
Посмотрите во втором разделе статью о декоративной и контентной графике, еще раз посмотрите на все изображения в макете и задайтесь вопросом: что будет, если этого изображения на странице не будет? Можно ли его заменить текстом?
И еще раз проверьте названия файлов: они все должны быть маленькими буквами, даже если это аббревиатуры.
В остальном же все отлично, думаю, скоро мы это задание закроем.

2022-06-09 16:23 UTC, jumile commented on catalog.html
> +              <!-- Логотип в макете собран из многиъх маленьких элементов, не поняла как в один объединить-->
Изображение должно быть здесь одно. Посмотрите в ретроспективе к разделу - там Николай показывает экспорт нескольких слоев как одного изображения. Время ~35.30.

2022-06-09 16:23 UTC, jumile commented on index.html
> +            <!-- Логотип в макете собран из многиъх маленьких элементов, не поняла как в один объединить-->
Изображение должно быть здесь одно. Посмотрите в ретроспективе к разделу - там Николай показывает экспорт нескольких слоев как одного изображения. Время ~35.30.

2022-06-09 16:23 UTC, jumile commented on index.html
> +            <img src="images/search.svg" width="18.05" height="18.1" alt="Поиск">
Это декоративная графика, так что в разметку ее не добавляем.

2022-06-09 16:23 UTC, jumile commented on index.html
> +            <img src="images/favorite.svg" width="18.05" height="17" alt="Избранное">
Это декоративная графика,  в разметку ее не добавляем. Посмотрите подробный материал вот здесь: https://htmlacademy.ru/blog/articles/content-or-decor-img

2022-06-09 16:23 UTC, jumile commented on index.html
> +    <img class="landscape-picture" src="images/sedona-background-mainpage.jpg" width="1200" height="485" alt="Фотография Седоны">
Это просто фон, будет декоративная графика.

2022-06-09 16:23 UTC, jumile commented on index.html
> +    <img class="sedona-better-than-grandcanyon" src="images/sedona.svg" width="456.7" height="212.77" alt="Седону. Седона лучше Гранд-Каньона">
Вот эти три картинки, которые как бы текст, лучше экспортировать как одну. Они же неотделимы одна от другой и нигде не будут использоваться раздельно. 
Когда указываете размеры, не надо писать дробные числа. Вы можете округлять. Ведь макет рисует дизайнер, он не всегда соблюдает принципы, которые нужны для верстки; он может их даже не знать.

2022-06-09 16:23 UTC, jumile commented on index.html
> +          <img class="advantages-living-picture" src="images/advantages/living.svg" width="75" height="72" alt="Жилье в Седоне">
Это иконка, декоративная графика.

2022-06-09 16:23 UTC, jumile commented on index.html
> +          <img class="advantages-food-picture" src="images/advantages/food.svg" width="74" height="70" alt="Питание в Седоне">
Все иконки в этом разделе относятся к декоративной графике, так что в разметку их не добавляем.

2022-06-09 16:23 UTC, jumile commented on catalog.html
> +              <img src="images/search.svg" width="18.05" height="18.1" alt="Поиск">
Иконки относятся к декоративной графике, их не надо добавлять в разметку.

2022-06-09 16:23 UTC, jumile commented on catalog.html
> +              <img src="images/arrow-to-the-right.svg" width="5.11" height="7.95" alt="Выбрано">
58 и 59 строки тоже декоративная графика.

2022-06-09 16:23 UTC, jumile commented on catalog.html
>          <div class="livingtype-list">
Этот раздел формы аналогичен разделу Инфраструктура. Но там fieldset, а здесь  div. fieldset в этом случае лучше, поскольку он добавляет структуру форме.

2022-06-09 16:23 UTC, jumile commented on catalog.html
> +          <img src="images/arrow.svg" width="11.93" height="7.02" alt="Выбрано">
В строках 105-124 иконки будут добавляться через CSS, т.к. это тоже декоративная графика. Пока на эту мелочь время не тратьте, у вас дальше по курсу будет раздел по стилизации форм.

2022-06-09 16:23 UTC, jumile commented on catalog.html
> +        <img class="arrow-number-of-hotels-per-page" src="images/arrow.svg" width="11.93" height="7.02" alt="Варианты">
Это тоже через CSS, будет позже.

2022-06-10 10:38 UTC, sashadudkina5 commented on index.html
> +    <img class="sedona-better-than-grandcanyon" src="images/sedona.svg" width="456.7" height="212.77" alt="Седону. Седона лучше Гранд-Каньона">
Подскажите, пожалуйста, нужно ли вообще эти изображения вставлять в разметку? мне кажется, оно декоративное ...

2022-06-10 17:39 UTC, jumile commented on index.html
> +    <img class="sedona-better-than-grandcanyon" src="images/sedona.svg" width="456.7" height="212.77" alt="Седону. Седона лучше Гранд-Каньона">
Нет, это как раз нужно. Представьте, что его не будет. И как мы узнаем название сайта и что он вообще о Седоне?

2022-06-10 17:52 UTC, jumile approved these changes
Готово, поздравляю!

2022-06-10 17:52 UTC, merged

2022-06-10 20:16 UTC, sashadudkina5 commented on index.html
> +    <img class="sedona-better-than-grandcanyon" src="images/sedona.svg" width="456.7" height="212.77" alt="Седону. Седона лучше Гранд-Каньона">
спасибо!