Добавляет базовую стилизацию
htmlacademy-htmlcss/2097425-sedona-34 pull request #4
Opened 2022-06-11 18:10 UTC by sashadudkina5

2022-06-12 18:12 UTC, jumile requested changes
Очень хорошо, особенно для первого раза! Мне понравились ваши внимательность, аккуратность, отсутствие ошибок в свойствах.
Теперь над чем еще надо поработать. Разберитесь со стилями для преимуществ. Там каждое преимущество надо рассматривать как цельный блок, и соответственно задавать ему фон и прочие параметры.

Также еще раз посмотрите материалы по наследованию. Это позволит оптимизировать код для работы в будущем. У вас довольно много лишних строчек со свойствами, которые могут наследоваться.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    font-family: "PT Sans", sans-serif;
Желательно указать еще резервный шрифт из числа веб-безопасных.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    color:#000000;
Как вы думаете, а если не написать здесь фон и цвет текста, какие браузер поставит? И откуда он их возьмет?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    text-align: center;
По-моему, в макете не видно, что ссылки должны по центру выравниваться.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> + .number-of-favorites {
Обратите внимание на межбуквенный интервал в тексте с этим селектором.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    background-color: #FFFFFF;
А если не написать цвет фона и цвет текста, что будет?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    color: inherit;
Какой цвет текста будет, если не написать его здесь?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    font-size: 18px;
font-size - 18 или 10?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    color: #000000;
Если не написать здесь фон и цвет текста, какие они будут?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    font-weight: 400;
Какая будет у этого блока насыщенность текста, если не написать font-weight: 400?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    background-color: #83B3D3;
Проверьте номер цвета, пожалуйста.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    background-color: #83B3D3;
Проверьте номер цвета, пожалуйста.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    background-color: #FFFFFF;
Какие цвета для фона и текста поставит здесь браузер, если не писать? Откуда он их возьмет?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +.secect-dates {
Здесь нет опечатки? не select-dates?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +/** не поняла, почему  цвет ссыли не меняется **/
Посмотрите вот здесь: https://up.htmlacademy.ru/htmlcss/34/demos/7723#8
Вам нужно изменить селектор, для которого написаны стили по оформлению кнопки.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +h5 {
А вдруг h5 потом на сайте еще где-то встретится, но с другим оформлением? Может, сразу сделать такой селектор, чтобы потом не пришлось менять?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +.newsletter-button {
Посмотрите в браузере, какой шрифт у этой кнопки? Как это сделать: https://up.htmlacademy.ru/htmlcss/34/module/4/item/21
Кнопки в плане шрифта - хитрый элемент, об этом говорили на ретроспективе.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    background-color: #FFFFFF;
Посмотрите внимательно по поводу фона у body. Для этого в слоях можно выделить строку Главная страница - вот это и есть body в макете.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +.contact-number {
У гиперссылки надо еще удалить подчеркивание.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    font-weight: 700;
Если заголовку не указывать font-weight: 700;, он будет жирный? Почему?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +.search-hotel {
Какой шрифт применился к кнопкам search-hotel и reset-search?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    color: #000000;
Цвет текста обязательно нужен? Почему?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    font-weight: 400;
font-weight точно нужен?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +
Не хватает  оформления для кнопок показа каталога (Показ в виде галереи, Список ...)?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    color: #000000;
Цвет текста точно нужен? Что будет, если его не написать?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    font-weight: 400;
Нужно ли?

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +.pagination-link {
Здесь фона не хватает

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +.pagination-current {
Здесь тоже не хватает фона.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    font-weight: 400;
Нужно ли здесь указывать font-weight?

2022-06-12 18:12 UTC, jumile commented on index.html
> +    <img class="welcome-text" src="images/welcome.svg" width="458" height="352" alt="Добро пожаловать в Седону">
Этому изображению не хватает выравнивания по центру. Подумайте, как это можно сделать.

2022-06-12 18:12 UTC, jumile commented on index.html
>            <h3>Жильё</h3>
Этот и следующий заголовки должный быть заглавными буквами. Кроме того, у пунктов Жилье, Еда, Сувениры нужны декоративные значки перед заголовками.

2022-06-12 18:12 UTC, jumile commented on index.html
>          <li class="advantages-item">
Обратите внимание на цвет фона у блоков с преимуществами.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +    background-color: #000000;
Черный цвет фона задан для всего футера. Но в блоках с контактами у нас черный цвет текста - он не будет виден на черном фоне. Это нужно обязательно исправить.

2022-06-12 18:12 UTC, jumile commented on styles/styles.css
> +.product-card-button {
Текст на кнопках не должен быть подчеркнутым.

2022-06-14 12:46 UTC, sashadudkina5 commented on styles/styles.css
> +    color:#000000;
из body, поэтому это прописывать необзятально 
удалила

2022-06-14 12:48 UTC, sashadudkina5 commented on styles/styles.css
> +    background-color: #FFFFFF;
будут такие же, но будут перенесены из body по наследованию, поэтому прописывать здесь не нужно, удалила

2022-06-14 12:52 UTC, sashadudkina5 commented on index.html
> +    <img class="welcome-text" src="images/welcome.svg" width="458" height="352" alt="Добро пожаловать в Седону">
Сделала margin-left: auto;
    margin-right: auto;
    
    Но , может, надо просто через атрибут align на странице index? в чем будет разница?

2022-06-14 13:11 UTC, sashadudkina5 commented on index.html
>            <h3>Жильё</h3>
подскажите пожалуйста, а иконки вставлять в html страницу или в код css? если в css, то не совсем понимаю как:  в какой именно класс? и через какое значение? img? background-image?

2022-06-14 13:25 UTC, sashadudkina5 commented on styles/styles.css
> +    color: inherit;
мне кажется , что черный тк в классе advantages такие привила: background-color:#FFFFFF;
    color: #000000;

2022-06-14 13:36 UTC, sashadudkina5 commented on styles/styles.css
> +    color: #000000;
цвет текста - черный, фон - белый. Унаследуется от body 

удалила

2022-06-14 13:37 UTC, sashadudkina5 commented on styles/styles.css
> +    font-weight: 400;
не поняла, а font-weight: 400 ставится по умолчанию? я просто не прописывала его в body

2022-06-14 13:43 UTC, sashadudkina5 commented on styles/styles.css
> +    background-color: #FFFFFF;
из body 
удалила

2022-06-14 13:45 UTC, sashadudkina5 commented on styles/styles.css
> +    font-weight: 400;
как понять, какой font-weight подставляется автоматически ?

2022-06-14 14:00 UTC, sashadudkina5 commented on styles/styles.css
> +    color: #000000;
унаследуется такой же, удалила

2022-06-14 14:00 UTC, sashadudkina5 commented on styles/styles.css
> +    font-weight: 400;
как понять, какой font-weight подставляется автоматически ?

2022-06-14 14:01 UTC, sashadudkina5 commented on styles/styles.css
> +
не совсем поняла, как в css вставлять декоративные картинки и иконки, где про это можно посмотреть/почитать? подскажите пожалуйста
спасибо !

2022-06-14 14:02 UTC, sashadudkina5 commented on styles/styles.css
> +    color: #000000;
унаследуется из body

2022-06-14 14:04 UTC, sashadudkina5 commented on styles/styles.css
> +    font-weight: 700;
потому что у заголовков изначально итак font-weight 700, поэтому прописывать необязательно, удалила

2022-06-14 14:31 UTC, sashadudkina5 commented on styles/styles.css
> +.search-hotel {
должен быть PT Sans, а разве применился другой?

2022-06-14 14:33 UTC, sashadudkina5 commented on styles/styles.css
> +    background-color: #FFFFFF;
спасибо! поправила

2022-06-14 19:23 UTC, sashadudkina5 commented on styles/styles.css
> +.search-hotel {
разобралась

2022-06-15 10:07 UTC, jumile requested changes
Хорошо, но давайте доделаем все нюансы.

2022-06-15 10:07 UTC, jumile commented on index.html
>            <h3>Жильё</h3>
Эти иконки - декоративная графика. Это должен быть фон для блока с преимуществом. Какой это блок? Внутри которого находится вся информация по преимуществу - заголовок, текст.

2022-06-15 10:07 UTC, jumile commented on index.html
> +    <img class="welcome-text" src="images/welcome.svg" width="458" height="352" alt="Добро пожаловать в Седону">
img - строчный элемент. С помощью margin: auto; можно центрировать блочные элементы, элементы флекс и грид. Для строчных элементов нужно использовать другое центрирование, с помощью text-align, заданного родителю. Об этом есть вот здесь https://up.htmlacademy.ru/htmlcss/34/book/3.8 и еще на ретроспективе говорили.

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    font-family: "PT Sans", sans-serif, "Arial";
Сначала - основной шрифт, потом резервный, потом - семейство.

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    font-weight: 400;
В body его прописывать не нужно. font-weight: 400 - стандартное значение для текста, кроме заголовков и тегов strong, b. У них 700. font-weight пишут, когда его значения отличаются от стандартных.
То же самое - font-style. Его стандартное значение normal, и его не пишут для большинства элементов. А у тегов em, i, address и некоторых других стандартно font-style: italic, и это тоже не пишут.
Посмотрите еще ретро 4, где-то после 45-ой минуты.

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    color: inherit;
Ну да, он же наследуется, так что здесь прямое указание на наследование (inherit) лишнее.

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    background-color: #83B3D3;
Цвет #82B3D3;

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    font-family: PT Sans;
1) шрифт следует задавать по общим правилам - с указанием резервного и семейства. Кроме того, название шрифта из нескольких слов обязательно пишется в кавычках. 
2) в этом месте можно сделать по-другому, без явного указания шрифта, используя наследование.Только нужно прямо указать браузеру, что он должен унаследовать шрифт, а не применять встроенный.

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    font-family: "PT Sans";
Несмотря на то, что мы явно указываем для кнопки свой шрифт, мы все равно должны указать резервный (а вдруг этот не загрузится?) и обязательно семейство.
Ну и здесь, как и с предыд. кнопкой, можно явно указать наследование, а не сам шрифт. Вот как? https://up.htmlacademy.ru/htmlcss/34/module/4/item/10/7

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    font-weight: 400;
Я написала чуть выше про значения по умолчанию для font-weight

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +
Декоративные картинки - это фон. Про свойства фона можно посмотреть вот здесь: https://up.htmlacademy.ru/htmlcss/34/module/4/item/12/8

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    background-color: #FFFFFF;
А фон зачем?

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +.advantage-2, .advantage-4, .advantage-6, .advantage-8 {
Обратите внимание, что в блоках с преимуществами фон применился как будто только к заголовкам, а у абзацев остался темно-голубым. Сможете найти, почему так получилось? Вот так сейчас в браузере:
![image](https://user-images.githubusercontent.com/85567621/173789147-e88f8ba4-f25d-4a20-a0cb-33c6b2cd1875.png)

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +    background-color: #000000;
Посмотрите в макете, у нас на белом фоне должна быть вся нижняя часть футера, а не только номер телефона. Т.е. у этой части и у части с подпиской - разные фоны.

2022-06-15 10:07 UTC, jumile commented on catalog.html
>                <label for="pool">Бассейн</label>
Пожалуйста, проверьте размер шрифта у подписей.

2022-06-15 10:07 UTC, jumile commented on styles/styles.css
> +
Давайте разберемся с фоном страницы. В макете для body мы видим #F2F2F2, однако мы также видим, что почти все содержимое расположено на белом фоне. Как это реализовать? Надо добавить обертку для всей страницы и уже этой обертке поставить белый фон. И центрировать ее на странице. 
Посмотрите вот эту статью еще: https://up.htmlacademy.ru/htmlcss/34/book/5.10.2

2022-06-16 16:48 UTC, sashadudkina5 commented on catalog.html
>                <label for="pool">Бассейн</label>
проверила, 20px, как и в макете

2022-06-16 16:49 UTC, sashadudkina5 commented on styles/styles.css
> +.advantage-2, .advantage-4, .advantage-6, .advantage-8 {
не могу понять, почему так(

2022-06-16 17:15 UTC, sashadudkina5 commented on styles/styles.css
> +    font-family: "PT Sans", sans-serif, "Arial";
здесь так и написано, или я как-то не так понимаю?

2022-06-17 08:48 UTC, jumile approved these changes
В целом готово, принимается!

2022-06-17 08:48 UTC, jumile commented on styles/styles.css
> +    font-family: "PT Sans", sans-serif, "Arial";
Шрифт - это конкретное название, например, PT Sans. Мы сначала пишем шрифт из макета, который придумал дизайнер, потом подбираем что-нибудь более стандартное, а в конце обязательно указываем семейство, т.е. некую общую группу, к которой относятся наши шрифты. В случае, если браузер не найдет ни одного из указанных нами шрифтов, он выберет у себя на компьютере другой шрифт из того же семейства. Шрифты одного семейства более-менее похожи между собой, так что замена будет не очень кардинальной. Подробнее о типах семейств можете почитать здесь: https://developer.mozilla.org/ru/docs/Web/CSS/font-family

2022-06-17 08:48 UTC, jumile commented on styles/styles.css
> +
Ширину поставьте точную, как в макете - 1200рх. Проценты - это относительная единица, вы пока их не проходите в этой части курса. 100% в данном случае - это фактически вся ширина окна браузера, вашего фона для body при этом видно не будет

2022-06-17 08:48 UTC, jumile commented on styles/styles.css
> +.advantage-2, .advantage-4, .advantage-6, .advantage-8 {
Смотрите, вы задали темно-голубой фон для абзацев - ниже у вас есть селектор .advantages .advantages-description. У него бОльший вес, чем у этого, поэтому к абзацу применился темный фон. Отслеживать это можно в консоли браузера на вкладке Элементы: находите нужный тег в html-коде и смотрите, какие селекторы и свойства на него влияют - браузер все показывает. Чем выше важность селектора, тем выше он написан в списке стилей. Можно "галочками" временно отключать свойства, чтобы смотреть, какой эффект они дают. Вот тут есть инструкция подробная: https://up.htmlacademy.ru/htmlcss/34/module/4/item/20

2022-06-17 08:48 UTC, jumile commented on catalog.html
>                <label for="pool">Бассейн</label>
Размер у подписей в форме все-таки 18, я имею в виду label.

2022-06-17 08:48 UTC, jumile commented on styles/styles.css
> +.number-hotels-found-perpage {
В этом селекторе не хватает жирности.

2022-06-17 08:49 UTC, merged

2022-06-18 12:52 UTC, sashadudkina5 commented on styles/styles.css
> +.advantage-2, .advantage-4, .advantage-6, .advantage-8 {
спасибо!