Сетка страниц и крупных блоков на флексах
htmlacademy-htmlcss/2097425-sedona-34 pull request #5
Opened 2022-06-20 09:14 UTC by sashadudkina5

---
:mortar_board: [Сетка страниц и крупных блоков на флексах](https://up.htmlacademy.ru/htmlcss/34/user/2097425/tasks/7)

2022-06-20 15:37 UTC, jumile requested changes
Вы на правильном пути, все получается!

2022-06-20 15:37 UTC, jumile commented on index.html
> +        <li>
зачем в отдел. пункт

2022-06-20 15:37 UTC, jumile commented on index.html
> +        <li>
зачем в отдел. пункт

2022-06-20 15:37 UTC, jumile commented on index.html
> +    <div class="main-page-container">
лишняя обертка?

2022-06-20 15:37 UTC, jumile commented on index.html
> +  <main class="main-index main-container">
один из классов лишний

2022-06-20 15:37 UTC, jumile commented on index.html
> +    <div class="footer-container">
лишняя обертка

2022-06-20 15:37 UTC, jumile commented on catalog.html
> +    <main class="main-inner main-container">
один из классов лишний

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    font-family: "PT Sans", sans-serif;
добавьте  веб-безопасный шрифт

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +  .main-page-container {
лишнее

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    width: 1200px;
лишнее

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    max-width: 300px;
ширина лишняя (пока)

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
>      /** Не поняла, как добавить две декоративные картинки. В одном правиле? **/
Для каждой ссылки - свой фон

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    flex-direction: row;
лишнее

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    justify-content: space-around;
лучше space-between + отступы для родителя

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    align-items: center; /** не понимаю, почему не работает вертикальное выравнивание **/
потому что заголовки белого цвета мешают

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    width: 720px;
лишнее

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    display: flex;
здесь флекс не нужен, ширина лишняя, а вот paddings добавьте

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +.product-list {
здесь лучше паддинги для пунктов списка, ширина лишняя.

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    flex-direction: row;
flex-direction и ширина лишние

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    flex-direction: row;
flex-direction лишнее

2022-06-20 15:37 UTC, jumile commented on styles/styles.css
> +    padding-right: 656px;  /* не понимаю, как сделать так, чтобы навигация по страницам не выезжала за край */
Выезжает из-за маркеров + у родителя не хватает паддингов
А вот padding-right: 656px;  не нужен

2022-06-23 19:57 UTC, sashadudkina5 commented
Кажется, все сделала, но липкий футер, как бы не пробовала, не получился... Сравнивала с записью консультации много раз и все равно что-то не то, но не пойму что именно...
Прикинула, как можно сделать блок с преимуществами: поделить все на дивы и флексы. Чуть-чуть сделала, но не уверена, что это правильное направление

2022-06-25 08:10 UTC, jumile approved these changes

2022-06-25 08:10 UTC, jumile commented on index.html
> +            <!-- Показывает ошибку, что в один ul нельзя вложить другой ul. Так ли это? Как тогда сделать вложенный список?-->
ul можно вложить в li. То есть в списке - обычный пункт, а внутри этого пункта - вложенный список.

2022-06-25 08:10 UTC, jumile commented on index.html
> +          <p><span class="visually-hidden">Контактный номер телефона</span></p>
span тут лишний, можно весь абзац скрыть. Или тогда p не нужен.

2022-06-25 08:10 UTC, jumile commented on styles/styles.css
> +    /* вот не знаю, как указать блокам высотуЧ, ведь нельзя поставить display block и flex одновременно */
У флексовых блоков height работает, так что можно смело использовать.

2022-06-25 08:10 UTC, jumile commented on styles/styles.css
> +    box-sizing: border-box;
Вы уже указали это свойство для селектора *, так что здесь уже не нужно, * замещает собой любой селектор.

2022-06-25 08:10 UTC, jumile commented on styles/styles.css
> +    display: block;
Ссылка с классом pagination-current одновременно имеет класс pagination-link - он уже у нас общий для всей пагинации. Поэтому display: block; по второму разу писать не нужно, свойство применится само.

2022-06-25 08:10 UTC, jumile commented on index.html
> +            </div> <!-- здесь попробовала сделать блок с перимуществами, добавила див-->
Хорошо.

2022-06-25 08:10 UTC, jumile commented on index.html
> +            <div class="column-direction">
Блокам с преимуществами не хватает отступов слева/справа.

2022-06-25 08:11 UTC, merged