Сетки компонентов на флексах
htmlacademy-htmlcss/2097425-sedona-34 pull request #6
Opened 2022-06-28 11:39 UTC by sashadudkina5

2022-06-29 09:32 UTC, jumile requested changes
Большая работа проделана, давайте "дотягивать" детали. Если что-то не понятно в комментариях - пишите в телеграм.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +    /* не понимаю, почему навигация съехала вниз */
Посмотрите на следующий список - там padding сверху и снизу, из-за них все содержимое  .navigation  опустилось вниз.

2022-06-29 09:32 UTC, jumile commented on index.html
> +            <ul class="navigation-main-items">
В этом разделе определитесь с расстояниями между пунктами меню и логотипом. Между пунктами надо уменьшить, а между логотипом и Главной - увеличить. 
Также будет правильно задать ширину меню, но не строго по макету, а предусмотреть место еще на 1 пункт меню - на случай, если он появится. 
Попробуйте добавить в меню несколько пунктов - штук 5 - как оно себя поведет? Не сломается ли верстка? Посмотрите, как тестировать мелкие сетки на переполнение: 
https://up.htmlacademy.ru/htmlcss/34/module/6/item/11 время ~8.23
https://up.htmlacademy.ru/htmlcss/34/demos/7447#5 и далее до 8 шага.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +    margin-botttom: 57px;
Это нужно, но здесь опечаточка, поэтому не работает.
Фон с фотографией лучше поставить этому блоку, а не main - так будет проще управлять отступами. Ведь для нас важно, чтобы рисунок с названием сайта стоял всегда на фоне фотографии. Вдруг в начало main понадобится добавить что-то еще - содержимое при этом сместится вниз, а фон останется на месте, и получится, что у вас на фоне уже не рисунок с названием сайта, а что-то другое. Поэтому лучше фон привязать к блоку с рисунком - так мы гарантируем, что рисунок всегда будет на этом фоне.

2022-06-29 09:32 UTC, jumile commented on index.html
>              <div class="column-direction">
Вот в этом месте сделано правильно - пункт списка, а внутри него содержимое. 
Сравните со строкой 104 - div не может напрямую вкладываться в ul, он может быть только внутри li. Я считаю, там вообще этот div лишний, нужно просто добиться в стилях, чтобы пункты списка шли так, как вам нужно. Хотя это не просто))

Во втором преимуществе поменяйте местами текст и картинку. Попробуйте сделать это, не изменяя разметку, через стили.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +/* не понимаю , как поместить иконки в преимуществах */
Когда текст накладывается на фон, его можно сдвинуть при помощи padding для того блока, которому задан фон. Но перед этим еще надо посмотреть на позиционирование для фона: он у вас сейчас по центру, а должен быть по центру только по горизонтали, а по вертикали - на расстоянии 80рх от верхнего края.

2022-06-29 09:32 UTC, jumile commented on index.html
>          <ul class="navigation-list navigation-user">
Обратите внимание на ширину кнопки Хочу сюда в этом блоке - ее лучше задать., т.к. без нее кнопка не получается нужного размера, как в макете. Еще эта кнопка не центрируется по вертикали. В консоли браузера посмотрите стили, которые влияют на эту кнопку, поотключайте их по очереди и посмотрите на поведение кнопки. Обратите внимание на min-height, заданное для всех пунктов этого списка.

2022-06-29 09:32 UTC, jumile commented on index.html
>            <input type="email" placeholder="Ваш e-mail" id="subscribe">
Текстовое поле и кнопку тоже уже можно сделать. Попробуйте сделать, чтобы они стояли рядом и были одинаковой высоты. Подсказка: высоту задавать не надо, элементы сами должны растянуться и стать одинаковой высоты.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +    /* не понимаю, почему кнопка "хочу сюда" не выровнялась */
Посмотрите мой комментарий к файлу index по поводу этой кнопки.
Вам нужно отказаться в этом списке от паддингов и от мин. высоты пункта с кнопкой и разобраться с выравниванием у флексовых элементов.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +    /*не понимаю, почему применилось ко всем пунктам списка, а не только к последнему" */
:last-child находит любой элемент, являющийся последним в его родителе. В каждом пункте списка - 1 гиперссылка, она и первая, и последняя, и единственная, поэтому :last-child  к ней и применяется.
В данном случае нам нужна не последняя гиперссылка, а ссылка в последнем ПУНКТЕ меню, поэтому селектор будет приблизительно такой: .navigation-list-item:last-child a - и вот тут он найдет последний элемент с классом navigation-list-item и внутри него отформатирует гиперссылку. При этом если окажется несколько блоков с классами navigation-list-item, то в каждом будет найден последний. Например, у нас несколько списков на странице. В каждом есть пункты с классом navigation-list-item. Вот внутри каждого списка будет взят последний пункт и если там окажется тег а, он будет стилизован.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
>  .advantages-list li:not(img) {
Что имеет в виду этот селектор? Пункт списка, который не рисунок?
Вообще, у вас все параметры текста преимуществ заданы в селекторе column-direction. Попробуйте отключить свойства вот этого селектора, и вы увидите, что ничего не изменится, поскольку работает column-direction.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +    margin: 0px;
При значении 0 единицы измерения можно не писать.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +    /* не понимаю, почему в некоторых преимуществах верхний отступ стал 80px */
Мне кажется, потому что вы его написали в 272 строке.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
>      background-repeat: no-repeat;
Эта стрелочка не должна быть фоном всему списку. Пока не нужно ее делать, в 8 разделе добавите.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +    background-image: url("../images/union.svg");
1) проверьте наличие рисунка
2) если у элемента нет никакого содержимого, его размеры считаются = 0 и фон просто не виден. Чтобы это исправить, надо элементу задать минимал. размеры.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
Настройте размер фона для блока .catalog-filters, чтобы фон растягивался под размер блока.

2022-06-29 09:32 UTC, jumile commented on styles/styles.css
> +    /* не понимаю, почему элемент не прижался к правому краю */
Он прижался, учитывая ширину и отступы родительского блока - посмотрите селектор filters-bottom-container

2022-06-29 09:32 UTC, jumile commented on catalog.html
>        <div class="footer-background">
Здесь не хватает расстояния между блоками

2022-06-29 09:32 UTC, jumile commented on catalog.html
> +                <a class="navigation-link navigation-link-current" href="#">Главная</a>
А куда делась ссылочка на index?

2022-06-29 11:54 UTC, sashadudkina5 commented on index.html
>              <div class="column-direction">
не понимаю, как без Дива сделать горизонтальное расположение блоков( Если удаляю див, то блоки встают вертикально друг за другом 
текст с картинкой поменяла с помощью order

2022-06-30 09:33 UTC, sashadudkina5 commented on styles/styles.css
Добавила правило background-size: cover;

2022-06-30 09:40 UTC, sashadudkina5 commented on styles/styles.css
> +    background-image: url("../images/union.svg");
получилось, спасибо!

2022-06-30 09:52 UTC, sashadudkina5 commented on styles/styles.css
>  .advantages-list li:not(img) {
да, хотела применить минимальные высоту и ширину к блокам но не к картинкам
применила к column-direction , вроде получилось 
спасибо!

2022-06-30 10:02 UTC, sashadudkina5 commented on styles/styles.css
> +    /*не понимаю, почему применилось ко всем пунктам списка, а не только к последнему" */
Спасибо!

2022-06-30 10:15 UTC, sashadudkina5 commented on index.html
> +            <ul class="navigation-main-items">
Добавила ширину 490px и сделала flex-wrap: wrap
протестировала: новые пункты один добавляется справа, остальные переносятся на новую строку

2022-06-30 15:41 UTC, jumile approved these changes
Все отлично!

2022-06-30 15:41 UTC, merged