Cетки на гридах
htmlacademy-htmlcss/2097425-sedona-34 pull request #7
Opened 2022-07-04 18:02 UTC by sashadudkina5

2022-07-04 18:36 UTC, jumile requested changes
Почти готово)
У блока footer-background-main-page поправьте размер фонового изображения.
Звездочки уже можно добавить в карточки.

2022-07-04 18:36 UTC, jumile commented on styles/styles.css
> +        /* почему-то p-price все равно попал не в ту ячейку*/
А я не вижу, чтобы вы указали, какую грид-область должны занимать эти абзацы. Поэтому они занимают просто одну ячейку в сетке.

2022-07-04 18:36 UTC, jumile commented on styles/styles.css
> +}
Эти 2 селектора не срабатывают, потому что они не для того, что вам нужно. Попробуйте использовать :nth-of-type или просто класс.

2022-07-04 18:36 UTC, jumile commented on styles/styles.css
> +h3 {
Всем h3 отступы обнуляем? А не радикально? А если еще где-то h3 возникнет (за пределами карточек отелей)?

2022-07-04 20:50 UTC, sashadudkina5 commented on styles/styles.css
> +        /* почему-то p-price все равно попал не в ту ячейку*/
> 

подскажите, пожалуйста, а что не так с фоновым изображением footer-background-main-page ? Не совсем понятен этот момент . Сделала ширину 1200 как в макете

2022-07-04 21:07 UTC, sashadudkina5 commented on styles/styles.css
> +        /* почему-то p-price все равно попал не в ту ячейку*/
Я думала звездочки добавить в разделе про декоративные элементы, пока что не совсем понимаю , как наиболее корректно это можно сделать

2022-07-06 06:35 UTC, jumile approved these changes

2022-07-06 06:35 UTC, merged