Декоративные элементы всех страниц
htmlacademy-htmlcss/2097425-sedona-34 pull request #8
Opened 2022-07-07 14:49 UTC by sashadudkina5

Ирина, я вроде все сделала, но осталось 2 уточнения:
1) подскажите, пожалуйста, исконки соц. сетей и сайт разработчика лучше вставить в разметку как svg (как иконки в галвном меню), чтобы при смене состояния менялся цвет? сейчас стоят img 
2) не совсем поняла, где брать данные по outline для кнопок, не нашла в стайлгайде для focus-visible , везде проставила focus

2022-07-07 17:41 UTC, jumile requested changes
Отвечаю на вопросы:
1. Да, так как иконки будут меняться, лучше как svg.
2. Псевдокласс :focus-visible применяется у кнопок, когда элемент выбран с клавиатуры, т.е. фактически соответствует псевдоклассу :focus. Они могут выглядеть одинаково, но если мы для button стилизуем только focus, то focus-visible будет выглядеть по-другому, как захочет браузер. Это вполне ОК, но есть одна проблема: стандартно у focus-visible всегда есть outline, который изменит размер кнопки, если в других состояниях у нее нет границы. А у нас как раз нет, и если оставить focus-visible стандартным, то при выборе с клавиатуры кнопка будет увеличиваться, нам это не нужно. Поэтому кнопкам надо добавить псевдокласс :focus-visible, сделать его таким же, как :focus и дополнительно убрать outline.
Примеры и сравнение разных состояний можно посмотреть здесь: https://developer.mozilla.org/ru/docs/Web/CSS/:focus-visible
Примеры стилизации outline: https://developer.mozilla.org/en-US/docs/Web/CSS/outline

Иконки поиска и избранного - просто идеальны!

2022-07-07 17:41 UTC, jumile commented on styles/styles.css
> +    background-color: ##82B3D3;
Поправьте цвет, лишний #

2022-07-07 17:41 UTC, jumile commented on styles/styles.css
> +    border: 2px solid #000;
Кнопки отображения карточек - вы все сверстали правильно, но тут есть один момент, который, наверное, пока для вас неочевиден. Первая кнопка, у которой черная рамка - почему она черная? В стайлгайде есть нажатие и наведение с черной рамкой, но в макете состояния не рисуют. Здесь черная рамка у кнопки показывает, что мы сейчас выбрали именно этот вариант отображения -  в виде галереи. Можно предположить, что когда мы выберем вариант "списком", черная рамка будет у другой кнопки. В данном случае это не состояние элемента, а подсказка посетителю, где он находится. Похоже на коричневую полоску в главном меню. А как у нас там сделано? Там это особый класс, который применен к конкр. пункту меню. Этот класс будет ставиться автоматически через JavaScript, но наша задача его предусмотреть. Так что предлагаю черную рамку вынести в отдельный класс и добавить его первой кнопке - из расчета, что при переключении на другой вид отображения класс также будет применен к другой кнопке.

2022-07-07 17:41 UTC, jumile commented on styles/styles.css
> +.logo {
Логотип получился не совсем так, как в макете. Абсолютное позиционирование лучше задать не рисунку, а его родителю.

2022-07-07 17:41 UTC, jumile commented on styles/styles.css
> +    bottom: -26px;
У вас эта коричневая линия по-разному выглядит на Главной странице и в Каталоге. Поставьте здесь высоту 2 рх, а границу задайте только нижнюю и прижмите элемент к нижнему краю - просто 0.

2022-07-08 17:56 UTC, sashadudkina5 commented on styles/styles.css
> +    border: 2px solid #000;
Поняла, спасибо!
Добавила класс vision-current

2022-07-08 19:23 UTC, jumile approved these changes

2022-07-08 19:23 UTC, jumile commented on styles/styles.css
> +    position: relative;
лишняя строчка

2022-07-08 19:24 UTC, jumile commented
Все отлично! Продолжаем в прежнем темпе.

2022-07-08 19:24 UTC, merged