Попапы, слайдеры, формы
htmlacademy-htmlcss/2097425-sedona-34 pull request #9
Opened 2022-07-09 18:44 UTC by sashadudkina5

2022-07-09 20:04 UTC, jumile commented on styles/styles.css
> +.price-range label:nth-last-of-type(2) {
last-of-type - это последний, а если с номером, то nth-of-type

2022-07-09 20:04 UTC, jumile commented on styles/styles.css
> +    background: #E6E6E6;
:disabled еще нужен

2022-07-09 20:04 UTC, jumile commented on styles/styles.css
> +    /* не понимаю, почему это свойство унаследовалось всем остальным элементам */
Элемент стал прозрачным и все его содержимое тоже.

2022-07-09 20:04 UTC, jumile commented on styles/styles.css
> +.price-range-input {
Шрифт здесь поменялся или стандартный остался?

2022-07-09 20:04 UTC, jumile commented on styles/styles.css
> +    box-shadow: 0px 0px 0px 3px #81B3D2;
Если хотите с помощью тени, то сделайте ее внутренней - добавьте  inset.

2022-07-10 12:46 UTC, sashadudkina5 commented on styles/styles.css
> +    box-shadow: 0px 0px 0px 3px #81B3D2;
Внутри получилось сделать, спасибо! Но тогда внешняя тень пропадает:( Не понимаю, как сделать, чтобы тень была и внутри и снаружи элемента одновременно

2022-07-12 07:58 UTC, jumile requested changes
Ну все, последний рывок остался! 
Не хватает активного состояния для текстовых полей - в подписке и в модальном окне.
Не забудьте добавить класс для скрытия модального окна.
Подправляйте последние детали и вперед!

2022-07-12 07:58 UTC, jumile commented on styles/styles.css
> +    padding-right: 40px;
По макету здесь отступ 70рх - обратите внимание, что содержимое модального окна имеет одинаковое расстояние слева и справа до края, а у Вас получается справа явно меньше. Также увеличьте расстояние от правого края для кнопки Закрыть, чтобы кнопка и поля были ровно относительно друг друга.

2022-07-12 07:58 UTC, jumile commented on styles/styles.css
> +    right: 40px;
Вот здесь тоже расстояние поправьте до 70рх, пожалуйста.

2022-07-12 07:58 UTC, jumile commented on styles/styles.css
> +.modal-close-button:focus-visible {
Вы для всех состояний этой кнопки задаете изменение фона именно для круга - svg circle - это правильно. А вот для focus и focus-visible почему-то для самой кнопки. Из-за этого изменений не происходит. Фон кнопки, может, и меняется, но круг остается #f2f2f2, потому что для него есть правило,и у этого правила более высокий приоритет. Сделайте состояния фокуса также для круга.

2022-07-12 07:58 UTC, jumile commented on styles/styles.css
> +.modal-close-button:active svg.close-button-modal circle {
Этот селектор сейчас не работает, поскольку в разметке у Вас svg.close-button-icon
Вообще, все селекторы, связанные с этой кнопкой, можно сократить: необязательно перечислять все промежуточные элементы в селекторе, если они ни на что не влияют. Можно написать .modal-close-button:active  circle - все равно попадете на тот же круг.

2022-07-12 07:58 UTC, jumile commented on styles/styles.css
> +.modal-close-button:active svg.close-button-modal path {
Этот селектор тоже сейчас не срабатывает из-за несовпадения с разметкой.

2022-07-12 07:58 UTC, jumile commented on styles/styles.css
> +.adults-children-input-buttons {
В этом селекторе отступы не нужны. Из-за них у вас кнопки плюса и минуса получаются очень большими, у них странно выглядит outline в фокусе + очень высокая строка в основной сетке получается, она не совпадет с пиксель перфект. Так что отступы здесь лучше просто стереть.

2022-07-12 07:58 UTC, jumile commented on styles/styles.css
> +}
Обратите внимание на расстояние между строками сетки. Оно у вас сейчас побольше, чем в макете. Потому что мин. высота строки 40 + нижний отступ 11. Все-таки в макете абзац с ошибкой 30рх. Если оставить, как есть, все строки в модальном окне съедут и не совпадут с макетом в пиксель перфект.

2022-07-12 07:58 UTC, jumile commented on index.html
> +              <input class="modal-form-input" type="text" placeholder="Укажите дату" value="27 апреля 2020"
placeholder здесь как раз дата, а value нет. Если оставить, как у вас, во-первых, всегда будет сразу же выскакивать ошибка, поскольку дата в прошлом; во-вторых, value отправляется на сервер. Т.е. даже если посетитель ничего не введет, текстовое поле будет считаться заполненным и форма отправиться даже при случайном нажатии.

2022-07-12 07:58 UTC, jumile commented on index.html
> +              <button class="calendar-button button">
По критериям, атрибут type обязателен для button. Кстати, у вас сейчас форма отправляется при нажатии на календарик, потому что по умолчанию type=submit. Согласитесь, нестандартное поведение для кнопки выбора даты, так давайте подпишем правильный вариант.

2022-07-12 07:58 UTC, jumile commented on index.html
> +              <button class="calendar-button button">
Тоже не хватает типа кнопке.

2022-07-12 07:58 UTC, jumile commented on index.html
> +                <button class="modal-amount-guests-button modal-amount-guests-minus button">
Здесь тоже потерялся атрибут type.

2022-07-12 07:58 UTC, jumile commented on index.html
> +                <button class="tooltip-button button" aria-labelledby="tooltip-label" type="button">
Снова потерялся тип для кнопки и традиционная подсказка для скринридеров с visually-hidden

2022-07-12 07:58 UTC, jumile commented on catalog.html
> +        <section class="select-controls-section">
Тег section рекомендуется начинать с заголовка. Если он здесь не нужен, то лучше заменить на div.
И еще в 175 строчке аналогично.

2022-07-12 15:25 UTC, sashadudkina5 commented
Ирина, вроде все сделала, осталось 2 вопроса:
1) stylelint показывает много ошибок "Expected indentation of 2 spaces", но у меня никак не получается понять, что именно это за ошибка, как именно должно быть
2)Добавила класс кнопке для скрытия модального окна "hide" , по аналогии как с "current", я правильно поняла задачу?
Спасибо

2022-07-12 18:49 UTC, jumile requested changes
Я очень рада, что у вас практически все готово! 
Обратите внимание: в конце каждого файла с кодом должна быть пустая строка.
Создайте класс, который будет скрывать содержимое при помощи display: none и примените его к модальному окну.
Проверьте критерий CSS-03. У вас встречается 3 уровня вложенности.
Также посмотрите критерий ALLY-02. Получается, у всех alt и .visually-hidden надо поставить точку
Саша, изображения Sedona, Welcome и Souvenir.svg - с большой буквы. Все буквы в именах файлов и папок должны быть маленькими.

2022-07-12 18:49 UTC, jumile commented on catalog.html
> +                <label class="price-range-label"><input class="price-range-input" type="number" value="0"
Сделайте вложенные теги с новой строки. Обязательно сделайте Format document перед коммитом.

2022-07-12 18:49 UTC, jumile commented on catalog.html
> +
Уберите пустые строки здесь и в след. button

2022-07-12 18:49 UTC, jumile commented on catalog.html
>            <a href="#" class="button-vision button-show-gallery vision-current">
Атрибут class должен быть первым - поправьте в кнопках отображения.

2022-07-12 18:49 UTC, jumile commented on catalog.html
> +          <form class="filters-catalog-form" action="#" method="get">
Допишите значение в action

2022-07-12 18:49 UTC, jumile commented on catalog.html
>      <footer>
Уровни заголовков рекомендуется использовать по порядку. У вас нет h4, но сразу идет h5. Правильнее будет изменить, h5 повысить до h4, h6 до h5. Еще у вас в index и в catalog для соцсетей разный уровень заголовков оказался.

2022-07-12 18:49 UTC, jumile commented on styles/styles.css
> +.newsletter-button:hover,
Обратите внимание: основной селектор .newsletter-button (без состояний) у вас идет ниже, чем селекторы с состояниями. Порядок состояний важен, он может даже повлиять на вид элементов. Поэтому сначала обычное, потом visited (если есть), hover, focus, active.
То же самое - с иконками соцсетей, .search-hotel и еще у многих селекторов, проверьте, пожалуйста.

2022-07-12 18:49 UTC, jumile commented on styles/styles.css
> +.infrustructure-item-input[type="checkbox"]:checked+.control-mark-checkbox {
Пробелов не хватает вокруг плюса. Остальные селекторы с плюсом тоже поправьте.

2022-07-12 18:49 UTC, jumile commented on styles/styles.css
>  }
Лишние пробелы при определении грид-областей. Отступ должен быть = 2 пробелам, а не 4.

2022-07-12 18:49 UTC, jumile commented on styles/styles.css
> +
Уберите лишние пустые строки, пожалуйста.

2022-07-12 18:49 UTC, jumile commented on styles/styles.css
> +    box-shadow: 0px 15px 30px rgba(0, 0, 0, 0.3);
Удалите пиксели после 0.

2022-07-12 18:49 UTC, jumile commented on styles/styles.css
>  .list-of-advantages-main {
Этот список не прошел проверку на переполнение пунктами. Попробуйте добавить туда еще 1 пункт.
То же самое - список .second-part-advantages-list

2022-07-13 05:59 UTC, sashadudkina5 commented on styles/styles.css
>  .list-of-advantages-main {
Добавила flex-wrap: wrap;

2022-07-13 06:06 UTC, sashadudkina5 commented
изображения Sedona, Welcome и Souvenir.svg у меня везде с маленькой буквы - в разметке, в VS code , в папке сами файлы, не понимаю, где именно они продолжают отображаться с большой буквы и как это поправить (

2022-07-13 07:08 UTC, jumile approved these changes

2022-07-13 07:08 UTC, merged